### ISSUE TITLE
installation difficulty

### ISSUE THREAD

**Issue by nrnhines** [MetaCell/NEURON-UI#16]
I have ubuntu 16.4
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2

python install.py
got a long was but stopped at
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Installing Geppetto Jupyter Extension ...
Traceback (most recent call last):
  File "install.py", line 76, in <module>
    run_nbextension_install(False)
  File "install.py", line 10, in run_nbextension_install
    from notebook.nbextensions import install_nbextension_python, enable_nbextension_python, install_nbextension
ImportError: No module named notebook.nbextensions

pip install --upgrade pip
was successful but
$ python install.py
Cloning Geppetto Jupyter (Python package)...
fatal: destination path 'org.geppetto.frontend.jupyter' already exists and is not an empty directory.
Checking out development branch for Geppetto Jupyter ...
M	src/geppettoJupyter/geppetto
Already on 'development'
Your branch is up-to-date with 'origin/development'.
error: pathspec 'integratingPlot' did not match any file(s) known to git.
Cloning Geppetto Neuron Configuration ...
fatal: destination path 'geppetto-neuron' already exists and is not an empty directory.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Enabling Geppetto Neuron Configuration ...
...
Installing Geppetto Jupyter Extension ...
Enabling geppettoJupyter extensions ...
Installing geppettoJupyter extension ...
Traceback (most recent call last):
  File "install.py", line 76, in <module>
    run_nbextension_install(False)
  File "install.py", line 22, in run_nbextension_install
    install_nbextension_python('geppettoJupyter', symlink=develop)
  File "/home/hines/.local/lib/python2.7/site-packages/notebook/nbextensions.py", line 239, in install_nbextension_python
    destination=dest, logger=logger
  File "/home/hines/.local/lib/python2.7/site-packages/notebook/nbextensions.py", line 140, in install_nbextension
    ensure_dir_exists(nbext)
  File "/home/hines/.local/lib/python2.7/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/share/jupyter'

**Comment by tarelli** [comment]
@nrnhines Hi Michael, could you try installing with sudo python install.py ? I see a permission denied error and that might be it (the jupyter extension needs super user privileges to install). Let me know how it goes!

**Comment by nrnhines** [comment]
Hi Mateo,
I'm sure that will work. But do I want to install NEURON-UI as root? Is everything
going into my python installation. I would have liked to keep this project segregated
so I could easly uninstall with 'rm'.

________________________________________

**Comment by tarelli** [comment]
@nrnhines Let me look into it, we need to find a way to install a jupyter extension without being root. I believe it should be possible. We can also add an uninstall script that removes the extension from a jupyter install.

**Comment by tarelli** [comment]
@nrnhines Hi Michael, with the latest master branch it should work without sudo. Note that if you previously installed using sudo you might still seem some errors due to some files being created with the root user previously (the fix if that happens is to chown them). Next week we will release the new version with a lot of improvements and more features in case you want to wait for that to have a look.

**Comment by nrnhines** [comment]
That did the trick.
Thanks!
-Michael

________________________________________

**Comment by tarelli** [comment]
Great!
